ndk

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,4 +1,19 @@
-# (C) 2015 Cybozu.  All rights reserved.
+if test -n "$ngx_module_link"; then
+    if test -n "$NDK_SRCS"; then
+        echo "found ngx_devel_kit for ngx_encrypted_session; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_encrypted_session; please put it before ngx_http_uuid4." 1>&2
+        exit 1
+    fi
+else
+    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
+        echo "found ngx_devel_kit for ngx_encrypted_session; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_encrypted_session; please put it before ngx_http_uuid4." 1>&2
+        exit 1
+    fi
+fi
+
 
 ngx_addon_name="ngx_http_uuid4"
 
@@ -16,4 +31,4 @@ else
     NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_uuid4.c"
 fi
 
-# vim: ft=sh
+CFLAGS="$CFLAGS -DNDK_SET_VAR"
